// SPDX-License-Identifier: Apache-2.0

package scaffold

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/dsgnr/datum/internal/discover"
	"github.com/dsgnr/datum/internal/document"
)

// The point of generating a repository is that it reconciles as it stands, so the
// test that matters is discovery reading what was written.
func TestGeneratedRepositoryIsDiscovered(t *testing.T) {
	dir := t.TempDir()
	if _, err := Write(dir, Files("example", false)); err != nil {
		t.Fatal(err)
	}

	result, err := discover.Walk(dir)
	if err != nil {
		t.Fatalf("discovery failed on a generated repository: %v", err)
	}
	if result.Set.Fleet.Name != "example" {
		t.Errorf("fleet = %q, want example", result.Set.Fleet.Name)
	}
	if len(result.Set.Layers) != 1 || result.Set.Layers[0].Name != "base" {
		t.Errorf("layers = %+v, want one named base", result.Set.Layers)
	}
	if len(result.Set.Resources) != 0 {
		t.Errorf("resources = %+v, want none", result.Set.Resources)
	}
}

func TestExamplesAreDiscovered(t *testing.T) {
	dir := t.TempDir()
	written, err := Write(dir, Files("example", true))
	if err != nil {
		t.Fatal(err)
	}
	if len(written) != 4 {
		t.Fatalf("wrote %d files, want 4: %v", len(written), written)
	}

	result, err := discover.Walk(dir)
	if err != nil {
		t.Fatalf("discovery failed with examples: %v", err)
	}
	if len(result.Set.Hosts) != 1 || result.Set.Hosts[0].Name != "example-host" {
		t.Errorf("hosts = %+v, want one named example-host", result.Set.Hosts)
	}
	if len(result.Set.Resources) != 1 {
		t.Fatalf("resources = %+v, want one", result.Set.Resources)
	}
	// The example resource has to land in the layer beside it, since that is the
	// one rule the comment in the file claims.
	if got := result.Set.Resources[0].Layer; got != "base" {
		t.Errorf("layer = %q, want base", got)
	}
}

// Datum writes the version it understands, so a repository generated by an agent
// always matches that agent.
func TestGeneratedDocumentsDeclareTheCurrentSchema(t *testing.T) {
	for _, file := range Files("example", true) {
		if !strings.Contains(file.Body, "datum: "+document.SchemaVersion+"\n") {
			t.Errorf("%s does not declare %s:\n%s", file.Path, document.SchemaVersion, file.Body)
		}
	}
}

func TestFleetNameIsUsed(t *testing.T) {
	dir := t.TempDir()
	if _, err := Write(dir, Files("platform", false)); err != nil {
		t.Fatal(err)
	}
	result, err := discover.Walk(dir)
	if err != nil {
		t.Fatal(err)
	}
	if result.Set.Fleet.Name != "platform" {
		t.Errorf("fleet = %q, want platform", result.Set.Fleet.Name)
	}
}

func TestWriteRefusesToOverwrite(t *testing.T) {
	dir := t.TempDir()
	existing := filepath.Join(dir, "fleet", "base", "layer.yaml")
	if err := os.MkdirAll(filepath.Dir(existing), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(existing, []byte("mine\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	if _, err := Write(dir, Files("example", false)); err == nil {
		t.Fatal("writing over an existing document should fail")
	}

	// Nothing at all should have been written, including the file that comes
	// before the clash.
	if body, err := os.ReadFile(existing); err != nil || string(body) != "mine\n" {
		t.Errorf("the existing file was modified: %q %v", body, err)
	}
	if _, err := os.Stat(filepath.Join(dir, "fleet", "datum.yaml")); !os.IsNotExist(err) {
		t.Errorf("fleet/datum.yaml was written despite the clash: %v", err)
	}
}

func TestWriteDoesNotLeavePartialDocumentsWhenAPathIsBlocked(t *testing.T) {
	dir := t.TempDir()
	blocked := filepath.Join(dir, "fleet", "base")
	if err := os.MkdirAll(filepath.Dir(blocked), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(blocked, []byte("not a directory\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	if _, err := Write(dir, Files("example", false)); err == nil {
		t.Fatal("writing should fail when a destination directory is blocked")
	}

	if _, err := os.Stat(filepath.Join(dir, "fleet", "datum.yaml")); !os.IsNotExist(err) {
		t.Errorf("fleet/datum.yaml was written despite the blocked path: %v", err)
	}
}
